const PRODUITS = [
  {
    id: 1,
    prodImage: "https://i.imgur.com/680pujy.png",
    title: "Shampoing sec 50cl",
    fournisseur: "Batiste",
    prix: "3,00€",
    description: "Il est unique comme vous et vos cheveux ! Idéal pour vous redonner une sensation de fraîcheur.",
  },
  {
    id: 2,
    prodImage: "https://i.imgur.com/LNp0fEi.png",
    title: "Serviettes hygiéniques",
    fournisseur: "Always",
    prix: "1,00€",
    description: "Les serviettes hygiéniques ALWAYS Maxi Long vous offrent une protection et un confort optimum quand vous en avez le plus besoin.",
  },
  {
    id: 3,
    prodImage: "https://i.imgur.com/56EQgQh.png",
    title: "Crème nourrissante",
    fournisseur: "Nivéa",
    prix: "2,50€",
    description: "La Crème nourrissante NIVEA est enrichie en Hydro-cires et Beurre de Karité pour hydrater intensément votre corps et votre visage pendant 24H.",
  },
  {
    id: 4,
    prodImage: "https://i.imgur.com/8JZDaOR.png",
    title: "Lingettes démaquillantes",
    fournisseur: "Evoluderm",
    prix: "3,50€",
    description: "Spécifiquement développées pour les peaux sensibles, ces lingettes offrent un démaquillage parfait à votre épiderme.",
  },
  {
    id: 5,
    prodImage: "https://i.imgur.com/2CJeitM.png ",
    title: "Gel hydroalcoolique",
    fournisseur: "Merci Handy",
    prix: "3,00€",
    description: "Les gels mains nettoyants de la marque Merci Handy sont des gels cosmétiques dont la fonction est de nettoyer vos mains et non pas de les désinfecter : ce ne sont pas des antibactériens.",
  },
  {
    id: 6,
    prodImage: "https://i.imgur.com/jyfGASM.png",
    title: "Chewing-gum",
    fournisseur: "Hollywood",
    prix: "3,00€",
    description: "Dégustez les chewing-gums historiques parfum chlorophylle menthe verte Hollywood Regular",
  },
  {
    id: 7,
    prodImage: "https://i.imgur.com/i379zBL.png",
    title: "Désinfectant pour écrans",
    fournisseur: "Hygie",
    prix: "3,00€",
    description: "Ce produit est adapté à tous les écrans plats, LCD, plasma, écran GPS, téléphone, écran de contrôles médicaux.",
  },
  {
    id: 8,
    prodImage: "https://i.imgur.com/dnnitwK.png",
    title: "Stick à lèvres",
    fournisseur: "Labello",
    prix: "2,25€",
    description: "La formule du Labello HYDRO CARE enrichie en huiles naturelles et Beurre de Karité offre une texture onctueuse qui fond instantanément sur vos lèvres et les laisse hydratées pendant 24h",
  },
  {
    id: 9,
    prodImage: "https://i.imgur.com/W9qGmEO.png",
    title: "Mouchoirs de poche",
    fournisseur: "Lotus",
    prix: "0,50€",
    description: "Les mouchoirs de poche Lotus sont conçus pour être à la fois très doux et très résistants.",
  },
  {
    id: 10,
    prodImage: "https://i.imgur.com/3ZpVZKe.png",
    title: "Déodorant 48H",
    fournisseur: "Nivéa",
    prix: "3,50€",
    description: "Avec son parfum inspiré de la Creme NIVEA le déodorant anti-transpirant Protect & Care éveille vos sens.",
  },
  {
    id: 11,
    prodImage: "https://i.imgur.com/bfMHXbE.png",
    title: "Eau de parfum",
    fournisseur: "Yves Rocher",
    prix: "3,50€",
    description: "L'Eau de Parfum Matin Blanc est une douce invitation à la paresse. Une note douce et réconfortante.",
  },
];

export { PRODUITS };